{% set name = "amazon-sagemaker-jupyter-scheduler" %}
{% set version = "3.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/amazon_sagemaker_jupyter_scheduler-{{ version }}.tar.gz
  sha256: 67480032c5c19fd807ae4c6cee91b168031f8d654447dc95b3097ed730ad81b9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - jupyter_packaging >=0.12.0,<0.13.dev0
    - setuptools >=40.8.0
    - wheel
    - pip
  run:
    - python >=3.7
    - aiobotocore ==2.7.*
    - jupyter-scheduler >2
    - jupyter_server
    - jupyterlab ==4.*
    - aws-embedded-metrics
    - async-timeout
    - async-lru
    - pydantic ==1.*

test:
  imports:
    - amazon_sagemaker_jupyter_scheduler
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://aws.amazon.com/sagemaker/
  summary: Amazon SageMaker Jupyter Scheduler based on the https://pypi.org/project/jupyter-scheduler/
  license: Apache-2.0
  license_file:
    - NOTICE
    - LICENSE

extra:
  recipe-maintainers:
    - oztoprakmustafa
    - zuoyuanh
